import WindE from "../svg/WindE.svg";
import WindS from "../svg/WindS.svg";
import WindW from "../svg/WindW.svg";
import WindN from "../svg/WindN.svg";
import DraW from "../svg/DragonWhite.svg";
import DraG from "../svg/DragonGreen.svg";
import DraR from "../svg/DragonRed.svg";
import Man1 from "../svg/Man1.svg";
import Man2 from "../svg/Man2.svg";
import Man3 from "../svg/Man3.svg";
import Man4 from "../svg/Man4.svg";
import Man5 from "../svg/Man5.svg";
import Man6 from "../svg/Man6.svg";
import Man7 from "../svg/Man7.svg";
import Man8 from "../svg/Man8.svg";
import Man9 from "../svg/Man9.svg";
import Pin1 from "../svg/Pin1.svg";
import Pin2 from "../svg/Pin2.svg";
import Pin3 from "../svg/Pin3.svg";
import Pin4 from "../svg/Pin4.svg";
import Pin5 from "../svg/Pin5.svg";
import Pin6 from "../svg/Pin6.svg";
import Pin7 from "../svg/Pin7.svg";
import Pin8 from "../svg/Pin8.svg";
import Pin9 from "../svg/Pin9.svg";
import Sou1 from "../svg/Sou1.svg";
import Sou2 from "../svg/Sou2.svg";
import Sou3 from "../svg/Sou3.svg";
import Sou4 from "../svg/Sou4.svg";
import Sou5 from "../svg/Sou5.svg";
import Sou6 from "../svg/Sou6.svg";
import Sou7 from "../svg/Sou7.svg";
import Sou8 from "../svg/Sou8.svg";
import Sou9 from "../svg/Sou9.svg";

import WindE_R from "../svg/WindE_R.svg";
import WindS_R from "../svg/WindS_R.svg";
import WindW_R from "../svg/WindW_R.svg";
import WindN_R from "../svg/WindN_R.svg";
import DraW_R from "../svg/DragonWhite_R.svg";
import DraG_R from "../svg/DragonGreen_R.svg";
import DraR_R from "../svg/DragonRed_R.svg";
import Man1_R from "../svg/Man1_R.svg";
import Man2_R from "../svg/Man2_R.svg";
import Man3_R from "../svg/Man3_R.svg";
import Man4_R from "../svg/Man4_R.svg";
import Man5_R from "../svg/Man5_R.svg";
import Man6_R from "../svg/Man6_R.svg";
import Man7_R from "../svg/Man7_R.svg";
import Man8_R from "../svg/Man8_R.svg";
import Man9_R from "../svg/Man9_R.svg";
import Pin1_R from "../svg/Pin1_R.svg";
import Pin2_R from "../svg/Pin2_R.svg";
import Pin3_R from "../svg/Pin3_R.svg";
import Pin4_R from "../svg/Pin4_R.svg";
import Pin5_R from "../svg/Pin5_R.svg";
import Pin6_R from "../svg/Pin6_R.svg";
import Pin7_R from "../svg/Pin7_R.svg";
import Pin8_R from "../svg/Pin8_R.svg";
import Pin9_R from "../svg/Pin9_R.svg";
import Sou1_R from "../svg/Sou1_R.svg";
import Sou2_R from "../svg/Sou2_R.svg";
import Sou3_R from "../svg/Sou3_R.svg";
import Sou4_R from "../svg/Sou4_R.svg";
import Sou5_R from "../svg/Sou5_R.svg";
import Sou6_R from "../svg/Sou6_R.svg";
import Sou7_R from "../svg/Sou7_R.svg";
import Sou8_R from "../svg/Sou8_R.svg";
import Sou9_R from "../svg/Sou9_R.svg";

import Blank from "../svg/Blank.svg";

const tileDra = [DraW, DraG, DraR];
const tileWind = [WindE, WindS, WindW, WindN];
const tileMan = [Man1, Man2, Man3, Man4, Man5, Man6, Man7, Man8, Man9];
const tilePin = [Pin1, Pin2, Pin3, Pin4, Pin5, Pin6, Pin7, Pin8, Pin9];
const tileSou = [Sou1, Sou2, Sou3, Sou4, Sou5, Sou6, Sou7, Sou8, Sou9];
const tileDra_R = [DraW_R, DraG_R, DraR_R];
const tileWind_R = [WindE_R, WindS_R, WindW_R, WindN_R];
const tileMan_R = [Man1_R, Man2_R, Man3_R, Man4_R, Man5_R, Man6_R, Man7_R, Man8_R, Man9_R];
const tilePin_R = [Pin1_R, Pin2_R, Pin3_R, Pin4_R, Pin5_R, Pin6_R, Pin7_R, Pin8_R, Pin9_R];
const tileSou_R = [Sou1_R, Sou2_R, Sou3_R, Sou4_R, Sou5_R, Sou6_R, Sou7_R, Sou8_R, Sou9_R];

export { tileDra, tileWind, tileMan, tilePin, tileSou, Blank };
export { tileDra_R, tileWind_R, tileMan_R, tilePin_R, tileSou_R };